Adapter cache service
Ouranosinc/Magpie pull request #388
Opened 2021-02-18 05:08 UTC by fmigneault

helps resolve bird-house/twitcher#97 
based on finding from https://github.com/bird-house/birdhouse-deploy/compare/cache-settings
and https://github.com/bird-house/twitcher/issues/97#issuecomment-780747482 

settings should be defined in `Twitcher` 's INI with something like: 

```
# caching settings for specific sections/functions
cache.regions = acl, service
cache.type = memory
cache.acl.expire = 60
cache.acl.enabled = true
cache.service.expire = 10
cache.service.enabled = true
```

2021-02-18 14:47 UTC, dbyrns requested changes
A little typo but everything else is good!

2021-02-18 14:47 UTC, dbyrns commented on magpie/adapter/magpieservice.py
> +                services.append(TwithcerService(url=service["service_url"],
Typo in class name `TwithcerService`

2021-02-18 14:49 UTC, dbyrns commented
Could you also contribute to https://github.com/bird-house/birdhouse-deploy/compare/cache-settings so that the `service` region is also properly configured?

2021-02-18 14:53 UTC, fmigneault commented on magpie/adapter/magpieservice.py
> +                services.append(TwithcerService(url=service["service_url"],
Well spotted :)

2021-02-18 14:55 UTC, fmigneault commented
> Could you also contribute to https://github.com/bird-house/birdhouse-deploy/compare/cache-settings so that the `service` region is also properly configured?

For the moment, that would give the wrong indication that caching is defined for services but it won't be working until Magpie 3.7 is integrated.

2021-02-18 15:00 UTC, dbyrns commented
Ok but we definitely not want to forget that piece of config when we will upgrade Magpie to 3.7

2021-02-18 15:01 UTC, dbyrns approved these changes, later dismissed
💯

2021-02-18 15:03 UTC, ldperron commented
> Ok but we definitely not want to forget that piece of config when we will upgrade Magpie to 3.7

We can already do the version bump and the config change in https://github.com/bird-house/birdhouse-deploy/compare/cache-settings , and issue the PR when 3.7 is ready.

2021-02-18 15:45 UTC, fmigneault commented
> 
> We can already do the version bump and the config change in https://github.com/bird-house/birdhouse-deploy/compare/cache-settings , and issue the PR when 3.7 is ready.

@ldperron 
Magpie has been sticking to 1.7.3 in birdhouse-deploy for way too long. 

Can be adjusted following https://github.com/bird-house/birdhouse-deploy/pull/102 and https://github.com/bird-house/birdhouse-deploy/pull/107 tests are passing, but everything seems to work for me with "3.7-dev".

@dbyrns 
> 
> Ok but we definitely not want to forget that piece of config when we will upgrade Magpie to 3.7

I will add it (doesn't hurt), but will also put a note as it won't take effect (contrary to `acl` one).

2021-02-18 16:30 UTC, tlvu submitted a review, later dismissed
Approve in principle only since I can not pull this version into PAVICS stack and test it.

2021-02-18 16:38 UTC, tlvu commented
> Can be adjusted following [bird-house/birdhouse-deploy#102](https://github.com/bird-house/birdhouse-deploy/pull/102) and [bird-house/birdhouse-deploy#107](https://github.com/bird-house/birdhouse-deploy/pull/107) tests are passing, but everything seems to work for me with "3.7-dev".

@fmigneault Something I meant to ask you but never got around to do it is why 2 separate PR to bump magpie in PAVICS stack?  Is one supposed to replace the other one?   At the end of the day, I suppose both will have the latest and greatest magpie with all the fixes so why 2 separate PR?

From the review perspective, it's confusing for me and double my review work.  I am not sure which one I need to prioritize.  You also added a notebook in the PAVICS-e2e-workflow-tests and I ended up asking you (https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/55#issuecomment-776772512) which of the 2 magpie PR the notebook was intended for.

2021-02-18 17:23 UTC, fmigneault commented
@tlvu 

> why 2 separate PR to bump magpie in PAVICS stack? Is one supposed to replace the other one? At the end of the day, I suppose both will have the latest and greatest magpie with all the fixes so why 2 separate PR?

Simply because I was not the author of bird-house/birdhouse-deploy#102 and I add even more features in bird-house/birdhouse-deploy#107 than was the first provides.
PR bird-house/birdhouse-deploy#107 is to be merged in bird-house/birdhouse-deploy#102, and the later in master (or whichever combination, as long as latest magpie is picked). 
Tests are against bird-house/birdhouse-deploy#107

2021-02-19 04:23 UTC, tlvu commented
> > 
> 
> Simply because I was not the author of [bird-house/birdhouse-deploy#102](https://github.com/bird-house/birdhouse-deploy/pull/102) and I add even more features in [bird-house/birdhouse-deploy#107](https://github.com/bird-house/birdhouse-deploy/pull/107) than was the first provides.
> PR [bird-house/birdhouse-deploy#107](https://github.com/bird-house/birdhouse-deploy/pull/107) is to be merged in [bird-house/birdhouse-deploy#102](https://github.com/bird-house/birdhouse-deploy/pull/102), and the later in master (or whichever combination, as long as latest magpie is picked).
> Tests are against [bird-house/birdhouse-deploy#107](https://github.com/bird-house/birdhouse-deploy/pull/107)

Oh right, those 2 PR opened for too long I forgot they are related and not separate PR.

So let's not add more "feature" to those 2 PR, only required fixes, get Jenkins test-suite to pass to ensure no regressions and merge those 2 PR.

There is also a Weaver PR opened.  I am guess we will focus on closing the Magpie first?

2021-02-20 08:49 UTC, fmigneault commented
@tlvu 
Magpie PRs are blocked mostly by other tests failing the test suite.
On one hand, we add security, but by adding it, other things that assumed open-bar data access breaks. 

As for Weaver one, it would be coming soon, when tests of https://github.com/crim-ca/weaver/pull/214 pass.

2021-03-01 21:11 UTC, merged