allow case sensitive regex matches for the `MAGPIE_USER_NAME_EXTRA_REGEX` setting
Ouranosinc/Magpie pull request #594
Opened 2023-10-25 14:31 UTC by mishaschwartz

Ensures that the settings/environment variable ``MAGPIE_USER_NAME_EXTRA_REGEX`` is case sensitive.

Previously, the check was case insensitive meaning that it could not be used to restrict usernames based on case.
For example, setting this value to `^[a-z]+$` would have permit the username `"someuser"` as well as `"Someuser"``. 

Now, the same regular expression will not match `"Someuser"` since case sensitivity in enforced.

2023-10-25 21:23 UTC, fmigneault requested changes
`param_compare=re.compile(...)` can be passed directly with any desired flags.
No need for the `regex_flags` parameter.

I like the idea of `re.X` being the default however, and not assume `re.I` by default.
All current regex used `[A-Za-z]` explicitly anyway, so they should still work with only `re.X`.

2023-10-25 21:23 UTC, fmigneault commented on tests/test_magpie_api.py
> +        utils.warn_version(self, "extra username regex added", "3.37", skip=True)
3.37.1 / versionchanged

2023-10-25 21:23 UTC, fmigneault commented on tests/interfaces.py
> +        utils.warn_version(self, "extra username regex added", "3.37", skip=True)
3.37.1

I think `versionchanged` is better here.

2023-10-26 20:28 UTC, fmigneault approved these changes
Looks good. Just waiting on tests to complete validation.

2023-10-27 13:12 UTC, mishaschwartz commented
@fmigneault  The tests are failing because `data.ceda.ac.uk` is unresponsive right now: https://github.com/Ouranosinc/Magpie/actions/runs/6655721960/job/18098444930?pr=594

2023-10-27 16:50 UTC, fmigneault commented
Validated that CEDA has planned down server until November 7.
Validated that tests and other checks than `links` run successfully.

2023-10-27 16:50 UTC, merged